### ISSUE TITLE
OpenJTalkSampleの使い方

### ISSUE THREAD

**Issue by jalpsjp** [nukacha/OpenJTalkSample#1]
OpenJtalkSampleを使わせていただこうと、Xcode 8.3.3、iPad Air2 iOS10.3.2で試してみましたが、OpenJTalk.bundleのリンク先にOpenJTalk.bundlがなく、またOpenJTalk.xcodeもリンク先につからず、赤字で表示されます。
　そして、Apple Mach-O Linker Errorがでて、実行できません。
よろしければ、このプロジェクトのコンパイル等のよるかたを教えていただけませんか。
　よろしくお願いします。

**Comment by nukacha** [comment]
ありがとうございます．

こちらでもコンパイルできないことを確認しました．
サブモジュールとなっていた一部のファイルがpushされていなかったようです．

修正したので，
現在あるこのプロジェクトのディレクトリを削除し，
再度cloneまたはダウンロードして試してみて，報告してくださると幸いです．

**Comment by jalpsjp** [comment]
早速のご返事ありがとうございます。
連休中に試してみました。
Xcode 8.3.3、iPad Air2 iOS10.3.2の環境で Implicit conversion losesなどの警告が出ましたが、コンパイルできました。
また、iPad上で再生もできました。
ありがとうございました。
